/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Graficacion;


import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author yetzr
 */
public class Estrellas4 extends javax.swing.JFrame {
    public static final int cuarto=100;
    static  final int ancho=400, largo=400, medio=200, alto=400;
    /**
     * Creates new form Estrellas4
     */
    public Estrellas4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estrellas4");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estrellas4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estrellas4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estrellas4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estrellas4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estrellas4().setVisible(true);
            }
        });
    }
    public void paint(Graphics g)
    {
        setBackground(Color.BLACK);
        g.setColor(Color.WHITE);
        g.drawLine(0, medio+32, ancho, medio+32);
        g.drawLine(medio, 0+32, medio, alto+32);
        
        g.drawLine(0, 0+32, ancho, 0+32);
        g.drawLine(0, alto+32, ancho, alto+32);
        g.drawLine(0, 0+32, 0, alto+32);
        g.drawLine(ancho, 0+32, ancho, alto+32);
        
        
        
        
        for(int i = 0; i < cuarto; i += 5)
        {
            //sector 2
            g.setColor(Color.MAGENTA);
            g.drawLine(cuarto, i+32, cuarto+i, cuarto+32);
            g.setColor(Color.MAGENTA);
            g.drawLine(cuarto, i+32, cuarto-i, cuarto+32);
            g.setColor(Color.MAGENTA);
            g.drawLine(cuarto, medio-i+32, cuarto-i, cuarto+32);
            g.setColor(Color.WHITE);
            g.drawLine(cuarto, medio-i+32, cuarto+i, cuarto+32);
            //sector 1
            g.setColor(Color.MAGENTA);
            g.drawLine(cuarto+medio, i+32, medio+cuarto+i, cuarto+32);
            g.setColor(Color.MAGENTA);
            g.drawLine(cuarto+medio, i+32, cuarto-i+medio, cuarto+32);
            g.setColor(Color.WHITE);
            g.drawLine(cuarto+medio, medio-i+32, cuarto-i+medio, cuarto+32);
            g.setColor(Color.MAGENTA);
            g.drawLine(cuarto+medio, medio-i+32, cuarto+i+medio, cuarto+32);
            //sector 3
            g.setColor(Color.WHITE);
            g.drawLine(cuarto, i+medio+32, cuarto+i, cuarto+medio+32);
            g.setColor(Color.MAGENTA);
            g.drawLine(cuarto, i+medio+32, cuarto-i, cuarto+medio+32);
            g.setColor(Color.MAGENTA);
            g.drawLine(cuarto, medio-i+medio+32, cuarto-i, cuarto+medio+32);
            g.setColor(Color.MAGENTA);
            g.drawLine(cuarto, medio-i+medio+32, cuarto+i, cuarto+medio+32);
            //sector 4
            g.setColor(Color.MAGENTA);
            g.drawLine(cuarto+medio, i+medio+32, medio+cuarto+i, cuarto+medio+32);
            g.setColor(Color.WHITE);
            g.drawLine(cuarto+medio, i+medio+32, cuarto-i+medio, cuarto+medio+32);
            g.setColor(Color.MAGENTA);
            g.drawLine(cuarto+medio, medio-i+medio+32, cuarto-i+medio, cuarto+medio+32);
            g.setColor(Color.MAGENTA);
            g.drawLine(cuarto+medio, medio-i+medio+32, cuarto+i+medio, cuarto+medio+32);
            
        }        
        
        /*
        for(int i = 0; i < medio; i += 5)
        {        
            //Sector 1
            g.setColor(Color.MAGENTA);
            g.drawLine(medio, i, medio+i, medio);
            //sector 2
            g.setColor(Color.BLUE);
            g.drawLine(medio, i, medio-i, medio);
            //sector 3
            g.setColor(Color.RED);
            g.drawLine(medio, alto-i, medio-i, medio);
            //sector 4
            g.setColor(Color.cyan);
            g.drawLine(medio, alto-i, medio+i, medio);
        } 
*/
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
