/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Graficacion;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author yaser
 */
public class LineaRecta extends javax.swing.JFrame {
    static  final int ancho=400, largo=400, medio=200, alto=400;
    
    /**
     * Creates new form LineaRecta
     */
    public LineaRecta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Linea Recta");
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LineaRecta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LineaRecta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LineaRecta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LineaRecta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LineaRecta().setVisible(true);
            }
        });
    }
    
    /**
     *
     * @param g
     */
    @Override
    public void paint (Graphics g) {
        //vamos a dibuhar el primer plano
        g.setColor(Color.red);
        //g.drawLine(medio, 0+32, medio, largo+32);//vertical
        //g.drawLine(0, medio+32, ancho, medio+32);//horizontal
        
       // g.drawLine(0, 0+32, largo, ancho+32);//pruebA 1
       // g.drawLine(largo, 0+32, 0, ancho+32);//prueba 2
  //estrella
  
        g.drawLine(0, largo+32, medio+10, 0+32);//prueba 2
  g.setColor(Color.MAGENTA);
        g.drawLine(medio-5, 0, largo, ancho+32);//prueba 2
  g.setColor(Color.green);
        g.drawLine(0, largo+32, ancho, medio-100);//prueba 2
  g.setColor(Color.CYAN);
        g.drawLine(ancho, largo+32, 0, medio-100);//prueba 2
   g.setColor(Color.red);
        g.drawLine(0, medio-100, largo, medio-100);//prueba 
  g.setColor(Color.blue);
        
  
  /*
     //estrella invertida
      g.drawLine(10, 0+32, medio, ancho+32);//prueba 3
      g.setColor(Color.blue);
      g.drawLine(10, 0+32, ancho, medio+100);//prueba 3
      g.setColor(Color.CYAN);
      //g.drawLine(0, 0, ancho, medio+100);//prueba 3
      g.drawLine(largo, 0+32, medio, ancho+32);//prueba 3
      g.setColor(Color.black);
      g.drawLine(largo, 0+32, -medio, largo+32);//prueba 3
      g.setColor(Color.DARK_GRAY);
      g.drawLine(0, medio+100, largo, medio+100);//prueba 3
      g.setColor(Color.ORANGE);
      */
      
        

        
        
        
        
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
