/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual2022A;

import javax.swing.JOptionPane;

/**
 *
 * @author yaser
 */
public class AlumnoVisual2022A extends javax.swing.JFrame {

    /**
     * Creates new form AlumnoVisuak2022A
     */
    public AlumnoVisual2022A() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnArchivo = new javax.swing.JMenu();
        btnRegresar = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        btnEdicion = new javax.swing.JMenu();
        btnAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso de Alumno");
        setBackground(new java.awt.Color(255, 0, 51));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 400, 370));
        setMaximumSize(new java.awt.Dimension(400, 370));
        setMinimumSize(new java.awt.Dimension(400, 370));
        setPreferredSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Agregar Alumno nuevo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 268, 49);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 260, 72, 22);

        lblNombre.setText("Nombre: ");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(10, 100, 100, 16);

        jLabel2.setText("Apellido Paterno: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 139, 110, 16);

        jLabel3.setText("Apellido Materno: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 180, 120, 16);

        jLabel4.setText("Fecha de Nacimiento: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 220, 140, 16);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(190, 90, 160, 35);
        getContentPane().add(txtApellidoPaterno);
        txtApellidoPaterno.setBounds(190, 130, 160, 35);
        getContentPane().add(txtApellidoMaterno);
        txtApellidoMaterno.setBounds(190, 170, 160, 35);
        getContentPane().add(txtDob);
        txtDob.setBounds(190, 210, 160, 35);

        btnArchivo.setText("Archivo");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        btnArchivo.add(btnRegresar);

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnSalir.setText("Salir");
        btnArchivo.add(btnSalir);

        jMenuBar1.add(btnArchivo);

        btnEdicion.setText("Edicion");
        jMenuBar1.add(btnEdicion);

        btnAyuda.setText("Ayuda");
        jMenuBar1.add(btnAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Visual2022A v20 = new Visual2022A();
        v20.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText().trim();
        if(nombre.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del estudiante", "aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String apellidoP = txtApellidoPaterno.getText().trim();
        if(apellidoP.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese el Apellido Paterno del estudiante", "aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String apellidoM = txtApellidoMaterno.getText().trim();
        if(apellidoM.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese el Apellido Materno del estudiante", "aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoVisual2022A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoVisual2022A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoVisual2022A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoVisual2022A.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnoVisual2022A().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnArchivo;
    private javax.swing.JMenu btnAyuda;
    private javax.swing.JMenu btnEdicion;
    private javax.swing.JMenuItem btnRegresar;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
