/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Grafico1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author yaser
 */
public class Abrir_Archivo extends javax.swing.JFrame {

    
    /**
     * Creates new form Abrir_Archivo
     */
    public Abrir_Archivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cargar_archivo = new javax.swing.JButton();
        txtArea_Fuente = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Abrir un archivo");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 600, 600));
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));

        btn_cargar_archivo.setText("Cargar archivo");
        btn_cargar_archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargar_archivoActionPerformed(evt);
            }
        });

        txtArea_Fuente.setEditable(false);
        txtArea_Fuente.setMaximumSize(new java.awt.Dimension(600, 600));
        txtArea_Fuente.setMinimumSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArea_Fuente, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cargar_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btn_cargar_archivo)
                .addGap(59, 59, 59)
                .addComponent(txtArea_Fuente, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cargar_archivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargar_archivoActionPerformed
        // TODO add your handling code here:
        
        //estoy creano mi vairable archivo de la clase jfilechooser, con el constructor vacio
        JFileChooser archivo = new JFileChooser();
        archivo.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        
        //filtro para permitir que solo acepte los archivos txt
        FileNameExtensionFilter txtfile = new FileNameExtensionFilter("Archivos de Texto plano .txt", "txt");
       
        //asigne el filtro al selector de archivos
        archivo.setFileFilter(txtfile);
        
        //el this hace referencia a esta misma clase
        int resultado = archivo.showOpenDialog(this);
        
        //aqui hacemos la comparacion 
        if(resultado!=JFileChooser.CANCEL_OPTION){
            File file = archivo.getSelectedFile();
            
            if(file==null || (file.getName().equals(""))){
                JOptionPane.showMessageDialog(rootPane, "La carga del archivo fue cancelada", 
                                                    "uups! algo malio sal",
                                                    JOptionPane.ERROR_MESSAGE);
            }else{
                    //txtArea_Fuente.setEditable(true);
                    //txtArea_Fuente.setText("algun texto aqui: "+file.getAbsolutePath());
                try{
                    FileReader fr = new FileReader(file.getAbsolutePath());
                    BufferedReader bf = new BufferedReader(fr);
                    String linea = bf.readLine();
                    String docfin="";
                    while(linea!=null){
                        
                        docfin+=linea;
                        docfin+="\n";
                        //System.out.println(linea);
                        linea=bf.readLine();
                    }
                    
                    bf.close();
                    txtArea_Fuente.setText(docfin);
                    }catch(Exception e){
                    e.printStackTrace();
                }
                
            }
        }else{
            
          JOptionPane.showMessageDialog(rootPane, "La carga del archivo fue cancelada", 
                                                    "uups! algo malio sal",
                                                    JOptionPane.ERROR_MESSAGE);
    
        }
        
        
    }//GEN-LAST:event_btn_cargar_archivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Abrir_Archivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Abrir_Archivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Abrir_Archivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Abrir_Archivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Abrir_Archivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cargar_archivo;
    private java.awt.TextArea txtArea_Fuente;
    // End of variables declaration//GEN-END:variables
}
