/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base_de_Datos;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import java.sql.Date;
/**
 *
 * @author yaser
 */
public class IngresarAlumno extends javax.swing.JFrame {

    /**
     * Creates new form IngresarAlumno
     */
    public IngresarAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblApellidoP = new javax.swing.JLabel();
        lblApellidoM = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        CbDia = new javax.swing.JComboBox<>();
        CbMes = new javax.swing.JComboBox<>();
        CbAño = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 410, 320));
        setMaximumSize(new java.awt.Dimension(410, 320));
        setMinimumSize(new java.awt.Dimension(410, 320));
        setPreferredSize(new java.awt.Dimension(410, 320));
        getContentPane().setLayout(null);

        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(10, 70, 110, 16);

        lblApellidoP.setText("Apellido Paterno");
        getContentPane().add(lblApellidoP);
        lblApellidoP.setBounds(10, 110, 110, 16);

        lblApellidoM.setText("Apellido Materno");
        getContentPane().add(lblApellidoM);
        lblApellidoM.setBounds(10, 160, 110, 16);

        lblDob.setText("Fecha de nacimiento");
        getContentPane().add(lblDob);
        lblDob.setBounds(10, 200, 110, 16);

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(130, 60, 280, 22);
        getContentPane().add(txtApellidoP);
        txtApellidoP.setBounds(130, 110, 280, 22);
        getContentPane().add(txtApellidoM);
        txtApellidoM.setBounds(130, 150, 280, 22);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(270, 250, 128, 22);

        CbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(CbDia);
        CbDia.setBounds(130, 200, 72, 22);

        CbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(CbMes);
        CbMes.setBounds(210, 200, 72, 22);

        CbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010" }));
        getContentPane().add(CbAño);
        CbAño.setBounds(320, 200, 72, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try{
        String Nombre=txtNombre.getText().trim(),ApellidoP=txtApellidoP.getText().trim(),ApellidoM=txtApellidoM.getText().trim();
        //choro del yetz
        String SDia=(String) CbDia.getSelectedItem(), SAño = (String) CbAño.getSelectedItem(),SMes = (String) CbMes.getSelectedItem();
        int Dia = Integer.parseInt(SDia),
         Mes = Integer.parseInt(SMes),
         Año = Integer.parseInt(SAño);
                

                
        //termina choro del yetz
       
       
        
        //esta mae hace el date pa la fecha si que si
        //no se como funciona la verdad, lo vimos en internet el yetz y yo
        Año=Año-1900;
        Date DoB = new Date(Año,Mes,Dia);
        
         
        
        if(Nombre.isEmpty()|ApellidoP.isEmpty()|ApellidoM.isEmpty()){
            JOptionPane.showMessageDialog(this, "Algunos o Todos los campos a llenar estan vacios","Error",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        Alumno al = new Alumno();
        al.InsertarAlumno(Nombre, ApellidoP, ApellidoM, DoB);
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error "+e );
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbAño;
    private javax.swing.JComboBox<String> CbDia;
    private javax.swing.JComboBox<String> CbMes;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
