/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SegundoParcial.Graficos;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author yaser
 */
public class CheckBoxes extends javax.swing.JFrame {

    /**
     * Creates new form CheckBoxes
     */
    public CheckBoxes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngOpciones = new javax.swing.ButtonGroup();
        chbPollo = new javax.swing.JCheckBox();
        chbJamon = new javax.swing.JCheckBox();
        chbPeperoni = new javax.swing.JCheckBox();
        lblTitulo = new javax.swing.JLabel();
        btnPreparar = new javax.swing.JButton();
        rbtnChica = new javax.swing.JRadioButton();
        rbtnGrande = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnArchivo = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        btnEdicion = new javax.swing.JMenu();
        btnAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CheckBoxes");
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        chbPollo.setText("Pollo");
        chbPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbPolloActionPerformed(evt);
            }
        });
        getContentPane().add(chbPollo);
        chbPollo.setBounds(30, 110, 50, 20);

        chbJamon.setText("Jamón");
        chbJamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbJamonActionPerformed(evt);
            }
        });
        getContentPane().add(chbJamon);
        chbJamon.setBounds(30, 150, 57, 20);

        chbPeperoni.setText("Peperoni");
        chbPeperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbPeperoniActionPerformed(evt);
            }
        });
        getContentPane().add(chbPeperoni);
        chbPeperoni.setBounds(30, 190, 87, 20);

        lblTitulo.setText("Seleccione al menos un ingrediente");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(70, 60, 220, 16);

        btnPreparar.setText("Preparar");
        btnPreparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrepararActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreparar);
        btnPreparar.setBounds(127, 280, 100, 22);

        btngOpciones.add(rbtnChica);
        rbtnChica.setText("Chica");
        rbtnChica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnChicaActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnChica);
        rbtnChica.setBounds(240, 120, 52, 30);

        btngOpciones.add(rbtnGrande);
        rbtnGrande.setText("Grande");
        rbtnGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGrandeActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnGrande);
        rbtnGrande.setBounds(240, 170, 61, 20);

        jLabel1.setText("Cantidad");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 90, 60, 16);

        btnArchivo.setText("Archivo");
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnSalir.setText("Salir");
        btnArchivo.add(btnSalir);

        jMenuBar1.add(btnArchivo);

        btnEdicion.setText("Edición");

        btnAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnAcercaDe.setText("Acerca de");
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });
        btnEdicion.add(btnAcercaDe);

        jMenuBar1.add(btnEdicion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
        JOptionPane.showMessageDialog(rootPane, 
        "Examen\n Yetzrai Abisai Vazquez Moreno \n 21AL7207489 \n Programación Visual", 
        "Información", 
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAcercaDeActionPerformed

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        int x = 1;
        x = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro de que quiere salir?");
        if(x == 0)
        {
        System.exit(0);
        }
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnPrepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrepararActionPerformed
        int pollo = 0, jamon = 0, peperoni = 0;
        int grande = 0, chica = 0;
        if(chbPollo.isSelected() || chbJamon.isSelected() || chbPeperoni.isSelected())
        {
            if(chbPollo.isSelected())
            {
                pollo = 1;
                System.out.println("Contiene el ingrediente: pollo");
            }if(chbJamon.isSelected())
            {
                jamon = 1;
                System.out.println("Contiene el ingrediente: jamón");
            }
            if(chbPeperoni.isSelected())
            {
                peperoni = 1;
                System.out.println("Contiene el ingrediente: peperoni");
            }
            if(rbtnChica.isSelected())
            {
                chica = 1;
                System.out.println("El tamaño de la orden es: chica");
            }
            if(rbtnGrande.isSelected())
            {
                grande = 1;
                System.out.println("El tamaño de la orden es: grande");
            }
        }else{
            chbPollo.setForeground(Color.red);
            chbJamon.setForeground(Color.red);
            chbPeperoni.setForeground(Color.red);
            rbtnChica.setForeground(Color.red);
            rbtnGrande.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar al menos un ingrediente", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_btnPrepararActionPerformed

    private void chbPolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbPolloActionPerformed
        chbPollo.setForeground(Color.black);
        chbJamon.setForeground(Color.black);
        chbPeperoni.setForeground(Color.black);
    }//GEN-LAST:event_chbPolloActionPerformed

    private void chbJamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbJamonActionPerformed
        chbPollo.setForeground(Color.black);
        chbJamon.setForeground(Color.black);
        chbPeperoni.setForeground(Color.black);
    }//GEN-LAST:event_chbJamonActionPerformed

    private void chbPeperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbPeperoniActionPerformed
        chbPollo.setForeground(Color.black);
        chbJamon.setForeground(Color.black);
        chbPeperoni.setForeground(Color.black);
    }//GEN-LAST:event_chbPeperoniActionPerformed

    private void rbtnChicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnChicaActionPerformed
        rbtnChica.setForeground(Color.black);
        rbtnGrande.setForeground(Color.black);
    }//GEN-LAST:event_rbtnChicaActionPerformed

    private void rbtnGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGrandeActionPerformed
        rbtnChica.setForeground(Color.black);
        rbtnGrande.setForeground(Color.black);
    }//GEN-LAST:event_rbtnGrandeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckBoxes().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAcercaDe;
    private javax.swing.JMenu btnArchivo;
    private javax.swing.JMenu btnEdicion;
    private javax.swing.JButton btnPreparar;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.ButtonGroup btngOpciones;
    private javax.swing.JCheckBox chbJamon;
    private javax.swing.JCheckBox chbPeperoni;
    private javax.swing.JCheckBox chbPollo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtnChica;
    private javax.swing.JRadioButton rbtnGrande;
    // End of variables declaration//GEN-END:variables
}
