/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SegundoParcial.Graficos;

import java.io.PushbackReader;
import javax.swing.JOptionPane;
import javax.swing.JSlider;

/**
 *
 * @author yaser
 * 
 */

public class Elementos1 extends javax.swing.JFrame {

    javax.swing.JSlider sldGrado = new JSlider(1, 6, 1);
   
    javax.swing.JLabel lblGrado = new javax.swing.JLabel("Selecciona el grado de la ecuación");
    javax.swing.JLabel lblSeleccionGrado = new javax.swing.JLabel(sldGrado.getValue() + "");
    javax.swing.JButton btnReseteo = new javax.swing.JButton("Reseteo");
    javax.swing.JButton btnDefinir = new javax.swing.JButton("Definir");

    javax.swing.JLabel lblGrado1 = new javax.swing.JLabel("grado 1");
    javax.swing.JLabel lblGrado2 = new javax.swing.JLabel("grado 2");
    javax.swing.JLabel lblGrado3 = new javax.swing.JLabel("grado 3");
    javax.swing.JLabel lblGrado4 = new javax.swing.JLabel("grado 4");
    javax.swing.JLabel lblGrado5 = new javax.swing.JLabel("grado 5");
    javax.swing.JLabel lblGrado6 = new javax.swing.JLabel("grado 6");
    javax.swing.JLabel lblconstante = new javax.swing.JLabel("constante");

    javax.swing.JFormattedTextField txtGrado6 = new javax.swing.JFormattedTextField();
    javax.swing.JFormattedTextField txtGrado5 = new javax.swing.JFormattedTextField();
    javax.swing.JFormattedTextField txtGrado4 = new javax.swing.JFormattedTextField();
    javax.swing.JFormattedTextField txtGrado3 = new javax.swing.JFormattedTextField();
    javax.swing.JFormattedTextField txtGrado2 = new javax.swing.JFormattedTextField();
    javax.swing.JFormattedTextField txtGrado1 = new javax.swing.JFormattedTextField();
    javax.swing.JFormattedTextField txtconstante = new javax.swing.JFormattedTextField();
    
    /**
     * Creates new form Elementos1
     */
    public Elementos1() {
        txtconstante.setValue(0);
        //sldGrado.setMaximum(6);
        //sldGrado.setMinimum(2);
        
        
        sldGrado.setMinorTickSpacing(1);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jpFormulario = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnArchivo = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        btnSlider = new javax.swing.JMenuItem();
        btnReset = new javax.swing.JMenuItem();
        btnEdicion = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elementos1");
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        jpFormulario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jpFormulario.setMaximumSize(new java.awt.Dimension(700, 600));
        jpFormulario.setMinimumSize(new java.awt.Dimension(700, 600));
        jpFormulario.setPreferredSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout jpFormularioLayout = new javax.swing.GroupLayout(jpFormulario);
        jpFormulario.setLayout(jpFormularioLayout);
        jpFormularioLayout.setHorizontalGroup(
            jpFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        jpFormularioLayout.setVerticalGroup(
            jpFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        getContentPane().add(jpFormulario);
        jpFormulario.setBounds(10, 20, 790, 670);

        btnArchivo.setText("Archivo");

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnArchivo.add(btnSalir);

        btnSlider.setText("Cargar Slider");
        btnSlider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSliderActionPerformed(evt);
            }
        });
        btnArchivo.add(btnSlider);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        btnArchivo.add(btnReset);

        jMenuBar1.add(btnArchivo);

        btnEdicion.setText("Edición");
        jMenuBar1.add(btnEdicion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int x=1;
        x = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro de que quiere salir?");
        if(x==0)
        {
        System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSliderActionPerformed
        
        
        jpFormulario.add(sldGrado);
        sldGrado.setBounds(40, 80, 250, 29);
        sldGrado.setLocation(40, 80);
        
        
        sldGrado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldGradoStateChanged(evt);
            }
        });
        
        
        jpFormulario.add(lblGrado);
        lblGrado.setBounds(40, 40, 350, 29);
        lblGrado.setLocation(40, 40);
        
        
        jpFormulario.add(lblSeleccionGrado);
        lblSeleccionGrado.setBounds(160, 95, 150, 29);
        lblSeleccionGrado.setLocation(160, 95);
        jpFormulario.add(btnReseteo);
        btnReseteo.setBounds(190, 200, 100, 29);
        btnReseteo.setLocation(190, 200);

        jpFormulario.add(btnDefinir);
        btnDefinir.setBounds(370, 200, 100, 29);
        btnDefinir.setLocation(370, 200);
        
        sldGrado.setValue(1);
        lblSeleccionGrado.setVisible(true);
        lblGrado.setVisible(true);
        sldGrado.setVisible(true);
        btnReseteo.setVisible(true);
        btnDefinir.setVisible(true);
    }//GEN-LAST:event_btnSliderActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        btnReseteo.setVisible(false);
        btnDefinir.setVisible(false);
        lblSeleccionGrado.setVisible(false);
        lblconstante.setVisible(false);
        txtconstante.setVisible(false);
        lblGrado.setVisible(false);
        sldGrado.setVisible(false);
        lblGrado1.setVisible(false);
        txtGrado1.setVisible(false);
        lblGrado2.setVisible(false);
        txtGrado2.setVisible(false);
        lblGrado3.setVisible(false);
        txtGrado3.setVisible(false);
        lblGrado4.setVisible(false);
        txtGrado4.setVisible(false);
        lblGrado5.setVisible(false);
        txtGrado5.setVisible(false);
        lblGrado6.setVisible(false);
        txtGrado6.setVisible(false);
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnReseteoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        txtconstante.setText("0");
        txtGrado1.setText("0");
        txtGrado2.setText("0");
        txtGrado3.setText("0");
        txtGrado4.setText("0");
        txtGrado5.setText("0");
        txtGrado6.setText("0");
    }   
    
    private void btnDefinirActionPerformed(java.awt.event.ActionEvent evt)
    {
        
    }
    
    
    
    private void sldGradoStateChanged(javax.swing.event.ChangeEvent evt) {
        
        btnReseteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReseteoActionPerformed(evt);
            }
        });
        
        
        
                lblSeleccionGrado.setText(sldGrado.getValue() + "");
                jpFormulario.add(lblconstante);
                lblconstante.setBounds(40, 120, 70, 29);
                lblconstante.setLocation(40, 120);
                jpFormulario.add(txtconstante);
                txtconstante.setBounds(40, 140, 50, 29);
                txtconstante.setLocation(40, 140);
        
        switch(sldGrado.getValue()) 
        {
            case 1:
                lblconstante.setVisible(true);
                txtconstante.setVisible(true);
                txtGrado1.setVisible(true);
                lblGrado1.setVisible(true);
                txtGrado1.setValue(0);
                jpFormulario.add(lblGrado1);
                lblGrado1.setBounds(120, 120, 50, 29);
                lblGrado1.setLocation(120, 120);
                jpFormulario.add(txtGrado1);
                txtGrado1.setBounds(120, 140, 50, 29);
                txtGrado1.setLocation(120, 140);
                lblGrado2.setVisible(false);
                txtGrado2.setVisible(false);
                
                txtGrado2.setValue(0);
                break;
            case 2:
                lblGrado2.setVisible(true);
                txtGrado2.setVisible(true);
                jpFormulario.add(lblGrado2);
                lblGrado2.setBounds(200, 120, 50, 29);
                lblGrado2.setLocation(200, 120);
                jpFormulario.add(txtGrado2);
                txtGrado2.setBounds(200, 140, 50, 29);
                txtGrado2.setLocation(200, 140);
                
                lblGrado3.setVisible(false);
                txtGrado3.setVisible(false);
                
                txtGrado3.setValue(0);
                break;
            case 3:
                lblGrado3.setVisible(true);
                txtGrado3.setVisible(true);
                
                jpFormulario.add(lblGrado3);
                lblGrado3.setBounds(280, 120, 50, 29);
                lblGrado3.setLocation(280, 120);
                jpFormulario.add(txtGrado3);
                txtGrado3.setBounds(280, 140, 50, 29);
                txtGrado3.setLocation(280, 140);
                
                lblGrado4.setVisible(false);
                txtGrado4.setVisible(false);
                txtGrado4.setValue(0);
                
                break;
            case 4:
                lblGrado4.setVisible(true);
                txtGrado4.setVisible(true);
                jpFormulario.add(lblGrado4);
                lblGrado4.setBounds(360, 120, 50, 29);
                lblGrado4.setLocation(360, 120);
                jpFormulario.add(txtGrado4);
                txtGrado4.setBounds(360, 140, 50, 29);
                txtGrado4.setLocation(360, 140);
                lblGrado5.setVisible(false);
                txtGrado5.setVisible(false);
                txtGrado5.setValue(0);
                break;
            case 5:
                lblGrado5.setVisible(true);
                txtGrado5.setVisible(true);
                jpFormulario.add(lblGrado5);
                lblGrado5.setBounds(440, 120, 50, 29);
                lblGrado5.setLocation(440, 120);
                jpFormulario.add(txtGrado5);
                txtGrado5.setBounds(440, 140, 50, 29);
                txtGrado5.setLocation(440, 140);
                lblGrado6.setVisible(false);
                txtGrado6.setVisible(false);
                txtGrado6.setValue(0);
                break;
            case 6:
                lblGrado6.setVisible(true);
                txtGrado6.setVisible(true);
                jpFormulario.add(lblGrado6);
                lblGrado6.setBounds(520, 120, 50, 29);
                lblGrado6.setLocation(520, 120);
                jpFormulario.add(txtGrado6);
                txtGrado6.setBounds(520, 140, 50, 29);
                txtGrado6.setLocation(520, 140);
                break;
            default:
        }
        
    }         
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elementos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elementos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elementos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elementos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elementos1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnArchivo;
    private javax.swing.JMenu btnEdicion;
    private javax.swing.JMenuItem btnReset;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem btnSlider;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jpFormulario;
    // End of variables declaration//GEN-END:variables


}
