package SegundoParcial.Graficos;

import java.awt.Component;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.File;
import javax.swing.JOptionPane;
import java.util.*;

/**
 *
 * @author yaser
 */
public class Evaluacion extends javax.swing.JFrame {

    static String docFin = "";
    static String nombre = "";
    static double progrmacionpro = 0;
    static double matematicaspro = 0;
    static double espanolpro = 0;
    static double inglespro = 0;
    static double promedio = 0;
    static int elec = 0;
    static String ruta = "C:\\Users\\yaser\\OneDrive\\Documentos";

    /**
     * Creates new form Evaluacion
     */
    public Evaluacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGTipoEvaluacion = new javax.swing.ButtonGroup();
        lblDecision = new javax.swing.JLabel();
        rbtnSemestre = new javax.swing.JRadioButton();
        rbtnCuatrimestre = new javax.swing.JRadioButton();
        cbMateria = new javax.swing.JComboBox<>();
        spnCalificacion = new javax.swing.JSpinner();
        spnSemana = new javax.swing.JSpinner();
        lblCalificacion = new javax.swing.JLabel();
        lblSemana = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnSiguiente = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new java.awt.TextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnArchivo = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        btnEdicion = new javax.swing.JMenu();
        btnAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evaluación");
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        lblDecision.setText("¿Semestre o cuatrimestre?");
        lblDecision.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDecision.setMaximumSize(new java.awt.Dimension(150, 20));
        lblDecision.setMinimumSize(new java.awt.Dimension(150, 20));
        lblDecision.setPreferredSize(new java.awt.Dimension(150, 20));
        getContentPane().add(lblDecision);
        lblDecision.setBounds(220, 10, 180, 40);

        btnGTipoEvaluacion.add(rbtnSemestre);
        rbtnSemestre.setText("Semestre");
        rbtnSemestre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        rbtnSemestre.setBorderPainted(true);
        rbtnSemestre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtnSemestre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbtnSemestre.setMaximumSize(new java.awt.Dimension(130, 55));
        rbtnSemestre.setMinimumSize(new java.awt.Dimension(130, 55));
        rbtnSemestre.setName(""); // NOI18N
        rbtnSemestre.setPreferredSize(new java.awt.Dimension(130, 55));
        rbtnSemestre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rbtnSemestre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rbtnSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSemestreActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnSemestre);
        rbtnSemestre.setBounds(120, 70, 130, 55);

        btnGTipoEvaluacion.add(rbtnCuatrimestre);
        rbtnCuatrimestre.setText("Cuatrimestre");
        rbtnCuatrimestre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        rbtnCuatrimestre.setBorderPainted(true);
        rbtnCuatrimestre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtnCuatrimestre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbtnCuatrimestre.setMaximumSize(new java.awt.Dimension(130, 55));
        rbtnCuatrimestre.setMinimumSize(new java.awt.Dimension(130, 55));
        rbtnCuatrimestre.setName(""); // NOI18N
        rbtnCuatrimestre.setPreferredSize(new java.awt.Dimension(130, 55));
        rbtnCuatrimestre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rbtnCuatrimestre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rbtnCuatrimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCuatrimestreActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnCuatrimestre);
        rbtnCuatrimestre.setBounds(310, 70, 130, 55);

        cbMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matemáticas", "Español", "Programación", "Inglés" }));
        cbMateria.setMaximumSize(new java.awt.Dimension(100, 30));
        cbMateria.setMinimumSize(new java.awt.Dimension(100, 30));
        cbMateria.setName(""); // NOI18N
        cbMateria.setPreferredSize(new java.awt.Dimension(100, 30));
        cbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(cbMateria);
        cbMateria.setBounds(470, 190, 110, 30);

        spnCalificacion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spnCalificacion.setMaximumSize(new java.awt.Dimension(100, 25));
        spnCalificacion.setMinimumSize(new java.awt.Dimension(100, 25));
        spnCalificacion.setName(""); // NOI18N
        spnCalificacion.setPreferredSize(new java.awt.Dimension(100, 25));
        getContentPane().add(spnCalificacion);
        spnCalificacion.setBounds(30, 260, 100, 25);

        spnSemana.setModel(new javax.swing.SpinnerNumberModel(1, 1, 24, 1));
        spnSemana.setMaximumSize(new java.awt.Dimension(100, 25));
        spnSemana.setMinimumSize(new java.awt.Dimension(100, 25));
        spnSemana.setName(""); // NOI18N
        spnSemana.setPreferredSize(new java.awt.Dimension(100, 25));
        getContentPane().add(spnSemana);
        spnSemana.setBounds(190, 260, 100, 25);

        lblCalificacion.setText("Calificación");
        lblCalificacion.setFocusable(false);
        lblCalificacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCalificacion.setMaximumSize(new java.awt.Dimension(100, 20));
        lblCalificacion.setMinimumSize(new java.awt.Dimension(100, 20));
        lblCalificacion.setName(""); // NOI18N
        lblCalificacion.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(lblCalificacion);
        lblCalificacion.setBounds(30, 240, 100, 20);

        lblSemana.setText("Semana");
        lblSemana.setFocusable(false);
        lblSemana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSemana.setMaximumSize(new java.awt.Dimension(100, 20));
        lblSemana.setMinimumSize(new java.awt.Dimension(100, 20));
        lblSemana.setName(""); // NOI18N
        lblSemana.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(lblSemana);
        lblSemana.setBounds(190, 240, 100, 20);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(330, 230));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(330, 230));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(550, 230));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setEnabled(false);
        txtArea.setMaximumSize(new java.awt.Dimension(300, 300));
        txtArea.setMinimumSize(new java.awt.Dimension(300, 300));
        txtArea.setPreferredSize(new java.awt.Dimension(500, 500));
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 320, 550, 230);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.setMaximumSize(new java.awt.Dimension(100, 25));
        btnSiguiente.setMinimumSize(new java.awt.Dimension(100, 25));
        btnSiguiente.setName(""); // NOI18N
        btnSiguiente.setPreferredSize(new java.awt.Dimension(100, 25));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente);
        btnSiguiente.setBounds(340, 260, 100, 25);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(470, 260, 100, 22);

        jLabel1.setText("Nombre completo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 170, 120, 16);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(30, 190, 320, 20);

        btnArchivo.setText("Achivo");

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnArchivo.add(btnSalir);

        jMenuBar1.add(btnArchivo);

        btnEdicion.setText("Edición");

        btnAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnAcercaDe.setText("Acerda de");
        btnEdicion.add(btnAcercaDe);

        jMenuBar1.add(btnEdicion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void rbtnCuatrimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCuatrimestreActionPerformed
        cbMateria.setSelectedIndex(0);
        spnSemana.setValue(1);
        btnSiguiente.setEnabled(true);
        spnSemana.setEnabled(true);
        txtArea.setText("");
        txtNombre.setEnabled(true);
    }//GEN-LAST:event_rbtnCuatrimestreActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

        if ("".equals(txtNombre.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Introduzca un nombre", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        switch (elec) {
            case 0:
                nombre = "";
                //matematicas
                if (!rbtnCuatrimestre.isSelected() && !rbtnSemestre.isSelected()) {
                    JOptionPane.showMessageDialog(rootPane, "Escoja un tipo de ciclo");
                    return;
                }
                espanolpro = 0;
                progrmacionpro = 0;
                inglespro = 0;
                matematicaspro += (int) spnCalificacion.getValue();
                nombre = txtNombre.getText();
                nombre = nombre.toUpperCase();
                docFin += "matmaticas: " + "nombre: " + nombre + " |semana: " + spnSemana.getValue() + " |calificacion: " + spnCalificacion.getValue() + "\n";
                txtArea.setText(docFin);
                //txtNombre.setText("");
                spnSemana.setValue((int) spnSemana.getValue() + 1);
                //spnCalificacion.setValue(0);

                if (rbtnSemestre.isSelected()) {
                    if ((int) spnSemana.getValue() > 24) {
                        spnSemana.setEnabled(false);
                        btnSiguiente.setEnabled(false);
                        spnSemana.setValue(24);
                    }
                }

                if (rbtnCuatrimestre.isSelected()) {
                    if ((int) spnSemana.getValue() > 16) {
                        spnSemana.setEnabled(false);
                        btnSiguiente.setEnabled(false);
                        spnSemana.setValue(16);
                    }
                }
                break;
            case 1:
                nombre = "";
                //español
                if (!rbtnCuatrimestre.isSelected() && !rbtnSemestre.isSelected()) {
                    JOptionPane.showMessageDialog(rootPane, "Escoja un tipo de ciclo");
                    return;
                }
                matematicaspro = 0;
                progrmacionpro = 0;
                inglespro = 0;
                espanolpro += (int) spnCalificacion.getValue();
                nombre = txtNombre.getText();
                nombre = nombre.toUpperCase();
                docFin += "Español: " + "nombre: " + nombre + " |semana: " + spnSemana.getValue() + " |calificacion: " + spnCalificacion.getValue() + "\n";
                txtArea.setText(docFin);
                //txtNombre.setText("");
                spnSemana.setValue((int) spnSemana.getValue() + 1);
                //spnCalificacion.setValue(0);

                if (rbtnSemestre.isSelected()) {
                    if ((int) spnSemana.getValue() > 24) {
                        spnSemana.setEnabled(false);
                        btnSiguiente.setEnabled(false);
                        spnSemana.setValue(24);
                    }
                }

                if (rbtnCuatrimestre.isSelected()) {
                    if ((int) spnSemana.getValue() > 16) {
                        spnSemana.setEnabled(false);
                        btnSiguiente.setEnabled(false);
                        spnSemana.setValue(16);
                    }
                }
                break;
            case 2:
                //programacion
                nombre = "";

                if (!rbtnCuatrimestre.isSelected() && !rbtnSemestre.isSelected()) {
                    JOptionPane.showMessageDialog(rootPane, "Escoja un tipo de ciclo");
                    return;
                }

                matematicaspro = 0;
                espanolpro = 0;
                inglespro = 0;
                progrmacionpro += (int) spnCalificacion.getValue();
                nombre = txtNombre.getText();
                nombre = nombre.toUpperCase();
                //txtNombre.setText("");
                docFin += "Programacion: " + "nombre: " + nombre + " |semana: " + spnSemana.getValue() + " |calificacion: " + spnCalificacion.getValue() + "\n";
                txtArea.setText(docFin);

                spnSemana.setValue((int) spnSemana.getValue() + 1);
                //spnCalificacion.setValue(0);

                if (rbtnSemestre.isSelected()) {
                    if ((int) spnSemana.getValue() > 24) {
                        spnSemana.setEnabled(false);
                        btnSiguiente.setEnabled(false);
                        spnSemana.setValue(24);
                    }
                }

                if (rbtnCuatrimestre.isSelected()) {
                    if ((int) spnSemana.getValue() > 16) {
                        spnSemana.setEnabled(false);
                        btnSiguiente.setEnabled(false);
                        spnSemana.setValue(16);
                    }
                }
                break;
            case 3:
                //ingles
                nombre = "";

                if (!rbtnCuatrimestre.isSelected() && !rbtnSemestre.isSelected()) {
                    JOptionPane.showMessageDialog(rootPane, "Escoja un tipo de ciclo");
                    return;
                }
                matematicaspro = 0;
                espanolpro = 0;
                progrmacionpro = 0;
                inglespro += (int) spnCalificacion.getValue();

                nombre = txtNombre.getText();
                nombre = nombre.toUpperCase();
                docFin += "Ingles: " + "nombre: " + nombre + " |semana: " + spnSemana.getValue() + " |calificacion: " + spnCalificacion.getValue() + "\n";
                txtArea.setText(docFin);
                // txtNombre.setText("");
                spnSemana.setValue((int) spnSemana.getValue() + 1);
                //spnCalificacion.setValue(0);

                if (rbtnSemestre.isSelected()) {
                    if ((int) spnSemana.getValue() > 24) {
                        spnSemana.setEnabled(false);
                        btnSiguiente.setEnabled(false);
                        spnSemana.setValue(24);
                    }
                }

                if (rbtnCuatrimestre.isSelected()) {
                    if ((int) spnSemana.getValue() > 16) {
                        spnSemana.setEnabled(false);
                        btnSiguiente.setEnabled(false);
                        spnSemana.setValue(16);
                    }
                }
                break;
            default:
                txtArea.setText("error");

        }
        txtArea.setEditable(false);
        spnSemana.setEnabled(false);
        spnSemana.setEnabled(false);
        txtNombre.setEnabled(false);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void rbtnSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSemestreActionPerformed
        cbMateria.setSelectedIndex(0);
        spnSemana.setValue(1);
        btnSiguiente.setEnabled(true);
        spnSemana.setEnabled(true);
        txtArea.setText("");
        spnCalificacion.setEnabled(true);
        txtNombre.setEnabled(true);
    }//GEN-LAST:event_rbtnSemestreActionPerformed

    private void cbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateriaActionPerformed
        spnSemana.setValue(1);
        spnCalificacion.setValue(0);
        btnSiguiente.setEnabled(true);
        spnSemana.setEnabled(true);
        spnCalificacion.setEnabled(true);
        Component a = cbMateria.getComponent(1);
        elec = cbMateria.getSelectedIndex();
        btnGuardar.setEnabled(true);

    }//GEN-LAST:event_cbMateriaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (rbtnSemestre.isSelected()) {
            File file = new File(ruta, "calificaciones.txt");
            try {
                FileWriter fw = new FileWriter(file.getAbsoluteFile(), true);
                BufferedWriter bw = new BufferedWriter(fw);
                if (!file.exists()) {
                    file.createNewFile();
                }
                nombre = "";
                nombre = txtNombre.getText();
                nombre = nombre.toUpperCase();
                switch (elec) {
                    case 0:
                        promedio = 0;
                        promedio = ((matematicaspro) / ((int) spnSemana.getValue()));
                        System.out.println((int) spnSemana.getValue());
                        System.out.println(promedio);
                        bw.write("semestre: " + "Nombre: " + nombre + " Promedio matematicas: " + promedio);
                        bw.newLine();
                        bw.close();
                        break;
                    case 1:
                        promedio = 0;
                        promedio = (espanolpro / (int) spnSemana.getValue());
                        bw.write("semestre: " + "Nombre: " + nombre + " Promedio español: " + promedio);
                        bw.newLine();
                        bw.close();
                        break;
                    case 2:
                        promedio = 0;
                        promedio = (progrmacionpro / (int) spnSemana.getValue());
                        bw.write("semestre: " + "Nombre: " + nombre + " Promedio programacion: " + promedio);
                        bw.newLine();
                        bw.close();
                        break;
                    case 3:
                        promedio = 0;
                        promedio = (inglespro / (int) spnSemana.getValue());
                        bw.write("semestre: " + "Nombre: " + nombre + " Promedio ingles: " + promedio);
                        bw.newLine();
                        bw.close();
                        break;

                    default:
                        txtArea.setText("error");
                }
            } catch (Exception e) {
                System.err.println(e);
            }
        } else {
            File file = new File(ruta, "Cua_calificaciones.txt");
            try {
                FileWriter fw = new FileWriter(file.getAbsoluteFile(), true);
                BufferedWriter bw = new BufferedWriter(fw);
                if (!file.exists()) {
                    file.createNewFile();
                }
                nombre = "";
                nombre = txtNombre.getText();
                nombre = nombre.toUpperCase();
                switch (elec) {
                    case 0:
                        promedio = 0;
                        promedio = ((matematicaspro) / ((int) spnSemana.getValue()));
                        System.out.println((int) spnSemana.getValue());
                        System.out.println(promedio);
                        bw.write("cuatrimestre: " + "Nombre: " + nombre + " Promedio matematicas: " + promedio);
                        bw.newLine();
                        bw.close();
                        break;
                    case 1:
                        promedio = 0;
                        promedio = (espanolpro / (int) spnSemana.getValue());
                        bw.write("cuatrimestre: " + "Nombre: " + nombre + " Promedio español: " + promedio);
                        bw.newLine();
                        bw.close();
                        break;
                    case 2:
                        promedio = 0;
                        promedio = (progrmacionpro / (int) spnSemana.getValue());
                        bw.write("cuatrimestre: " + "Nombre: " + nombre + " Promedio programacion: " + promedio);
                        bw.newLine();
                        bw.close();
                        break;
                    case 3:
                        promedio = 0;
                        promedio = (inglespro / (int) spnSemana.getValue());
                        bw.write("cuatrimestre: " + "Nombre: " + nombre + " Promedio ingles: " + promedio);
                        bw.newLine();
                        bw.close();
                        break;

                    default:
                        txtArea.setText("error");
                }
            } catch (Exception e) {
                System.err.println(e);
            }
        }

        txtArea.setText("");
        nombre = "";
        promedio = 0;
        docFin = "";
        progrmacionpro = 0;
        matematicaspro = 0;
        espanolpro = 0;
        inglespro = 0;
        promedio = 0;
        elec = 0;
        btnGuardar.setEnabled(false);
        btnSiguiente.setEnabled(true);
        
        spnSemana.setEnabled(true);

        try {
            cbMateria.setSelectedIndex(cbMateria.getSelectedIndex() + 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ya no hay materías", "Error", JOptionPane.ERROR_MESSAGE);
            txtNombre.setEnabled(false);
            spnCalificacion.setEnabled(false);
            spnSemana.setEnabled(false);
            btnSiguiente.setEnabled(false);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evaluacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAcercaDe;
    private javax.swing.JMenu btnArchivo;
    private javax.swing.JMenu btnEdicion;
    private javax.swing.ButtonGroup btnGTipoEvaluacion;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cbMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCalificacion;
    private javax.swing.JLabel lblDecision;
    private javax.swing.JLabel lblSemana;
    private javax.swing.JRadioButton rbtnCuatrimestre;
    private javax.swing.JRadioButton rbtnSemestre;
    private javax.swing.JSpinner spnCalificacion;
    private javax.swing.JSpinner spnSemana;
    private javax.swing.JTextArea txtArea;
    private java.awt.TextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
