package SegundoParcial.Graficos;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author yaser
 */
public class Menu extends javax.swing.JFrame {
    
    static String docfin = "";
    static String docfin2 = "";
    static String ruta = "C:\\Users\\yaser\\OneDrive\\Documentos";
    static int precio1 = 0;
    static int precio2 = 0;
    static int precio3 = 0;
    static int precio4 = 0;
    static int x = 0;
    static int y = 0;
    static int z = 0;
    static String docfin3="";
    static int docfin4=0;
    File file = new File(ruta, "ticket.txt");

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        RBopc1.setVisible(false);
        RBopc2.setVisible(false);
        RBopc3.setVisible(false);
        RBopc4.setVisible(false);
        ChBopc1.setVisible(false);
        ChBopc2.setVisible(false);
        ChBopc3.setVisible(false);
        TxtArea_fuente.setVisible(false);
        BtnMostrar.setVisible(false);
        BtnTerminar.setVisible(false);
        Btnproceder.setVisible(false);
        BtnLimpiar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Btnproceder = new javax.swing.JButton();
        CBmenu = new javax.swing.JComboBox<>();
        RBopc1 = new javax.swing.JRadioButton();
        RBopc2 = new javax.swing.JRadioButton();
        RBopc3 = new javax.swing.JRadioButton();
        RBopc4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        ChBopc1 = new javax.swing.JCheckBox();
        ChBopc2 = new javax.swing.JCheckBox();
        ChBopc3 = new javax.swing.JCheckBox();
        TxtArea_fuente = new java.awt.TextArea();
        BtnMostrar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBounds(new java.awt.Rectangle(0, 0, 600, 600));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 460, 630));
        setMaximumSize(new java.awt.Dimension(460, 630));
        setMinimumSize(new java.awt.Dimension(460, 630));
        setPreferredSize(new java.awt.Dimension(460, 630));

        jPanel1.setMaximumSize(new java.awt.Dimension(460, 620));
        jPanel1.setMinimumSize(new java.awt.Dimension(460, 620));
        jPanel1.setPreferredSize(new java.awt.Dimension(460, 620));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btnproceder.setText("Siguiente ->");
        Btnproceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnprocederActionPerformed(evt);
            }
        });
        jPanel1.add(Btnproceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 112, -1));

        CBmenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo:", "Snacks", "Tacos", "Hamburguesa ", "Tortas" }));
        CBmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBmenuActionPerformed(evt);
            }
        });
        jPanel1.add(CBmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 142, -1));

        Grupo1.add(RBopc1);
        RBopc1.setText("op1");
        jPanel1.add(RBopc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        Grupo1.add(RBopc2);
        RBopc2.setText("op2");
        jPanel1.add(RBopc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        Grupo1.add(RBopc3);
        RBopc3.setText("op3");
        jPanel1.add(RBopc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        Grupo1.add(RBopc4);
        RBopc4.setText("op4");
        jPanel1.add(RBopc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("MENU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 170, 60));

        ChBopc1.setText("jCheckBox1");
        jPanel1.add(ChBopc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        ChBopc2.setText("jCheckBox2");
        jPanel1.add(ChBopc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        ChBopc3.setText("jCheckBox3");
        jPanel1.add(ChBopc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        TxtArea_fuente.setEditable(false);
        jPanel1.add(TxtArea_fuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 210, 150));

        BtnMostrar.setText("Mostrar Ticket");
        BtnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 110, -1));

        BtnLimpiar.setText("Limpiar todo");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 390, 100, -1));

        BtnTerminar.setText("Agregar mas");
        BtnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTerminarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBmenuActionPerformed
        // TODO add your handling code here:

        switch (CBmenu.getSelectedIndex()) {
            case 0:
                ChBopc1.setSelected(false);
                ChBopc2.setSelected(false);
                ChBopc3.setSelected(false);
                ChBopc1.setVisible(false);
                ChBopc2.setVisible(false);
                ChBopc3.setVisible(false);
                TxtArea_fuente.setVisible(false);
                BtnMostrar.setVisible(false);
                BtnTerminar.setVisible(false);
                BtnLimpiar.setVisible(false);
                break;
            case 1:
                Btnproceder.setVisible(true);
                Btnproceder.setEnabled(true);
                ChBopc1.setSelected(false);
                ChBopc2.setSelected(false);
                ChBopc3.setSelected(false);
                ChBopc1.setVisible(false);
                ChBopc2.setVisible(false);
                ChBopc3.setVisible(false);
                TxtArea_fuente.setVisible(false);
                BtnMostrar.setVisible(false);
                BtnTerminar.setVisible(false);
                BtnLimpiar.setVisible(false);
                //se limpia la seleccion de los radio buton
                Grupo1.clearSelection();
                RBopc1.setVisible(true);
                RBopc2.setVisible(true);
                RBopc3.setVisible(true);
                RBopc4.setVisible(true);
                //se cambia el nombre
                RBopc1.setText("Helado: $15");
                RBopc2.setText("tostitos: $10");
                RBopc3.setText("chicarrones: $15");
                RBopc4.setText("Elote en vaso: $30");
                break;
            case 2:
                Btnproceder.setVisible(true);
                Btnproceder.setEnabled(true);
                ChBopc1.setSelected(false);
                ChBopc2.setSelected(false);
                ChBopc3.setSelected(false);
                ChBopc1.setVisible(false);
                ChBopc2.setVisible(false);
                ChBopc3.setVisible(false);
                TxtArea_fuente.setVisible(false);
                BtnMostrar.setVisible(false);
                BtnTerminar.setVisible(false);
                BtnLimpiar.setVisible(false);
                //se limpia la seleccion de los radio buton
                Grupo1.clearSelection();
                RBopc1.setVisible(true);
                RBopc2.setVisible(true);
                RBopc3.setVisible(true);
                RBopc4.setVisible(true);
                //se cambia el nombre
                RBopc1.setText("Orden de Suadero: $50");
                RBopc2.setText("Orden de Tripa: $70");
                RBopc3.setText("Orden de Bistec: $50");
                RBopc4.setText("Orden de Chorizo: $50");
                break;
            case 3:
                Btnproceder.setVisible(true);
                Btnproceder.setEnabled(true);
                ChBopc1.setSelected(false);
                ChBopc2.setSelected(false);
                ChBopc3.setSelected(false);
                
                ChBopc1.setVisible(false);
                ChBopc2.setVisible(false);
                ChBopc3.setVisible(false);
                TxtArea_fuente.setVisible(false);
                BtnMostrar.setVisible(false);
                BtnTerminar.setVisible(false);
                BtnLimpiar.setVisible(false);
                //se limpia la seleccion de los radio buton
                Grupo1.clearSelection();
                RBopc1.setVisible(true);
                RBopc2.setVisible(true);
                RBopc3.setVisible(true);
                RBopc4.setVisible(true);
                //se cambia el nombre
                RBopc1.setText("Beff burger: $150");
                RBopc2.setText("Cheeseburger: $100");
                RBopc3.setText("Spicy buffalo: $170");
                RBopc4.setText("Hawaiiana burger: $150");
                break;
            case 4:
                Btnproceder.setVisible(true);
                Btnproceder.setEnabled(true);
                ChBopc1.setSelected(false);
                ChBopc2.setSelected(false);
                ChBopc3.setSelected(false);
                ChBopc1.setVisible(false);
                ChBopc2.setVisible(false);
                ChBopc3.setVisible(false);
                TxtArea_fuente.setVisible(false);
                BtnMostrar.setVisible(false);
                BtnTerminar.setVisible(false);
                BtnLimpiar.setVisible(false);
                //se limpia la seleccion de los radio buton
                Grupo1.clearSelection();
                RBopc1.setVisible(true);
                RBopc2.setVisible(true);
                RBopc3.setVisible(true);
                RBopc4.setVisible(true);
                //se cambia el nombre
                RBopc1.setText("Torta de Pollo: $30");
                RBopc2.setText("Torta Ahogada: $25");
                RBopc3.setText("Torta de Queso: $20");
                RBopc4.setText("Torta de Atun: $25");
                break;
            default:
        }
    }//GEN-LAST:event_CBmenuActionPerformed

    private void BtnprocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnprocederActionPerformed
        // TODO add your handling code here:
        if (!RBopc1.isSelected() && !RBopc2.isSelected() && !RBopc3.isSelected() && !RBopc4.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "escoja una comida", "error", JOptionPane.ERROR_MESSAGE);
        } else {
            RBopc1.setVisible(false);
            RBopc2.setVisible(false);
            RBopc3.setVisible(false);
            RBopc4.setVisible(false);
            ChBopc1.setVisible(true);
            ChBopc2.setVisible(true);
            ChBopc3.setVisible(true);
            ChBopc1.setSelected(false);
            ChBopc2.setSelected(false);
            ChBopc3.setSelected(false);
            Btnproceder.setVisible(false);
            agarrar();
            BtnTerminar.setVisible(true);
            BtnLimpiar.setVisible(true);
        }
        

    }//GEN-LAST:event_BtnprocederActionPerformed

    private void BtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarActionPerformed
        // TODO add your handling code here:
        BtnLimpiar.setVisible(true);
        agarrar2();
        
        try {
            if (!file.exists()) {
                file.createNewFile();
            }
            
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            bw.write("Pedido: \n" + docfin3 + "\nTotal a pagar:" + docfin4 + "\n__________________");
           
            bw.newLine();
            bw.close();
            
        } catch (Exception e) {
            System.out.println("error");
        }
        
        TxtArea_fuente.setVisible(true);
        try {
            String Ak = "";
            
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String linea = br.readLine();
            while (linea != null) {
                Ak += linea;
                Ak += "\n";
                linea = br.readLine();
            }
            TxtArea_fuente.setText(Ak);
            br.close();
        } catch (Exception e) {
            
        }
        BtnTerminar.setVisible(false);
        ChBopc1.setVisible(false);
        ChBopc2.setVisible(false);
        ChBopc3.setVisible(false);
        CBmenu.setVisible(false);
        docfin="";
        docfin2="";
        docfin3="";
        docfin4=0;
    }//GEN-LAST:event_BtnMostrarActionPerformed

    private void BtnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTerminarActionPerformed
        // TODO add your handling code here:
        agarrar2();
        
        docfin3+=docfin;
        docfin4+=Integer.parseInt(docfin2);
        System.out.println(docfin4);
        switch (CBmenu.getSelectedIndex()) {
            case 0:
                ChBopc1.setSelected(false);
                ChBopc2.setSelected(false);
                ChBopc3.setSelected(false);
                ChBopc1.setVisible(false);
                ChBopc2.setVisible(false);
                ChBopc3.setVisible(false);
                TxtArea_fuente.setVisible(false);
                BtnMostrar.setVisible(true);
                BtnTerminar.setVisible(false);
                BtnLimpiar.setVisible(false);
                break;
            case 1:
                Btnproceder.setVisible(true);
                Btnproceder.setEnabled(true);
                ChBopc1.setSelected(false);
                ChBopc2.setSelected(false);
                ChBopc3.setSelected(false);
                ChBopc1.setVisible(false);
                ChBopc2.setVisible(false);
                ChBopc3.setVisible(false);
                TxtArea_fuente.setVisible(false);
                BtnMostrar.setVisible(true);
                BtnTerminar.setVisible(false);
                BtnLimpiar.setVisible(false);
                //se limpia la seleccion de los radio buton
                Grupo1.clearSelection();
                RBopc1.setVisible(true);
                RBopc2.setVisible(true);
                RBopc3.setVisible(true);
                RBopc4.setVisible(true);
                //se cambia el nombre
                RBopc1.setText("Helado: $15");
                RBopc2.setText("tostitos: $10");
                RBopc3.setText("chicarrones: $15");
                RBopc4.setText("Elote en vaso: $30");
                break;
            case 2:
                Btnproceder.setVisible(true);
                Btnproceder.setEnabled(true);
                ChBopc1.setSelected(false);
                ChBopc2.setSelected(false);
                ChBopc3.setSelected(false);
                ChBopc1.setVisible(false);
                ChBopc2.setVisible(false);
                ChBopc3.setVisible(false);
                TxtArea_fuente.setVisible(false);
                BtnMostrar.setVisible(true);
                BtnTerminar.setVisible(false);
                BtnLimpiar.setVisible(false);
                //se limpia la seleccion de los radio buton
                Grupo1.clearSelection();
                RBopc1.setVisible(true);
                RBopc2.setVisible(true);
                RBopc3.setVisible(true);
                RBopc4.setVisible(true);
                //se cambia el nombre
                RBopc1.setText("Orden de Suadero: $50");
                RBopc2.setText("Orden de Tripa: $70");
                RBopc3.setText("Orden de Bistec: $50");
                RBopc4.setText("Orden de Chorizo: $50");
                break;
            case 3:
                Btnproceder.setVisible(true);
                Btnproceder.setEnabled(true);
                ChBopc1.setSelected(false);
                ChBopc2.setSelected(false);
                ChBopc3.setSelected(false);
                
                ChBopc1.setVisible(false);
                ChBopc2.setVisible(false);
                ChBopc3.setVisible(false);
                TxtArea_fuente.setVisible(false);
                BtnMostrar.setVisible(true);
                BtnTerminar.setVisible(false);
                BtnLimpiar.setVisible(false);
                //se limpia la seleccion de los radio buton
                Grupo1.clearSelection();
                RBopc1.setVisible(true);
                RBopc2.setVisible(true);
                RBopc3.setVisible(true);
                RBopc4.setVisible(true);
                //se cambia el nombre
                RBopc1.setText("Beff burger: $150");
                RBopc2.setText("Cheeseburger: $100");
                RBopc3.setText("Spicy buffalo: $170");
                RBopc4.setText("Hawaiiana burger: $150");
                break;
            case 4:
                Btnproceder.setVisible(true);
                Btnproceder.setEnabled(true);
                ChBopc1.setSelected(false);
                ChBopc2.setSelected(false);
                ChBopc3.setSelected(false);
                ChBopc1.setVisible(false);
                ChBopc2.setVisible(false);
                ChBopc3.setVisible(false);
                TxtArea_fuente.setVisible(false);
                BtnMostrar.setVisible(true);
                BtnTerminar.setVisible(false);
                BtnLimpiar.setVisible(false);
                //se limpia la seleccion de los radio buton
                Grupo1.clearSelection();
                RBopc1.setVisible(true);
                RBopc2.setVisible(true);
                RBopc3.setVisible(true);
                RBopc4.setVisible(true);
                //se cambia el nombre
                RBopc1.setText("Torta de Pollo: $30");
                RBopc2.setText("Torta Ahogada: $25");
                RBopc3.setText("Torta de Queso: $20");
                RBopc4.setText("Torta de Atun: $25");
                break;
            default:
        }
        
    }//GEN-LAST:event_BtnTerminarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
        CBmenu.setVisible(true);
        RBopc1.setVisible(false);
        RBopc2.setVisible(false);
        RBopc3.setVisible(false);
        RBopc4.setVisible(false);
        ChBopc1.setVisible(false);
        ChBopc2.setVisible(false);
        ChBopc3.setVisible(false);
        TxtArea_fuente.setVisible(false);
        BtnMostrar.setVisible(false);
        BtnTerminar.setVisible(false);
        Btnproceder.setEnabled(false);
        BtnLimpiar.setVisible(false);
        CBmenu.setSelectedIndex(0);
        docfin="";
        docfin2="";
        docfin3="";
        docfin4=0;
        ChBopc1.setSelected(false);
        ChBopc2.setSelected(false);
        ChBopc3.setSelected(false);
        precio1=0;
        precio2=0;
        precio3=0;
        precio4=0;
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnMostrar;
    private javax.swing.JButton BtnTerminar;
    private javax.swing.JButton Btnproceder;
    private javax.swing.JComboBox<String> CBmenu;
    private javax.swing.JCheckBox ChBopc1;
    private javax.swing.JCheckBox ChBopc2;
    private javax.swing.JCheckBox ChBopc3;
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.JRadioButton RBopc1;
    private javax.swing.JRadioButton RBopc2;
    private javax.swing.JRadioButton RBopc3;
    private javax.swing.JRadioButton RBopc4;
    private java.awt.TextArea TxtArea_fuente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public String agarrar() {
        //snacks
        if (CBmenu.getSelectedIndex() == 1) {
            docfin = "";
            precio1 = 0;
            if (RBopc1.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                docfin = "";
                docfin += RBopc1.getText();
                precio1 = precio1 + 15;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("Chocolate: $3");
                ChBopc2.setText("Chispas: $3 ");
                ChBopc3.setText("Fresas: $5");
            }
            if (RBopc2.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                docfin = "";
                docfin += RBopc2.getText();
                precio1 = precio1 + 10;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("Chamoy: $5");
                ChBopc2.setText("Salchicha: $3");
                ChBopc3.setText("Cueritos: $3");
            }
            if (RBopc3.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                docfin = "";
                docfin += RBopc3.getText();
                precio1 = precio1 + 15;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("Salchica: $3");
                ChBopc2.setText("Chile: $5");
                ChBopc3.setText("Limon: $3");
            }
            if (RBopc4.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                docfin = "";
                docfin += RBopc4.getText();
                precio1 = precio1 + 30;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("Chile: $5");
                ChBopc2.setText("Limon: $3 ");
                ChBopc3.setText("sal: $3");
            }
        }
        //tacos
        if (CBmenu.getSelectedIndex() == 2) {
            docfin = "";
            precio2 = 0;
            if (RBopc1.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                docfin = "";
                docfin += RBopc1.getText();
                precio2 = precio2 + 50;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                
                ChBopc1.setText("Otra salsa: $5");
                ChBopc2.setText("Limon extra: $5 ");
                ChBopc3.setText("Tortilla extra: $10");
            }
            if (RBopc2.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                docfin = "";
                docfin += RBopc2.getText();
                precio2 = precio2 + 70;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                
                ChBopc1.setText("Otra salsa: $5");
                ChBopc2.setText("Limon extra: $5 ");
                ChBopc3.setText("Tortilla extra: $10");
            }
            if (RBopc3.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                docfin = "";
                docfin += RBopc3.getText();
                precio2 = precio2 + 50;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("Otra salsa: $5");
                ChBopc2.setText("Limon extra: $5 ");
                ChBopc3.setText("Tortilla extra: $10");
            }
            if (RBopc4.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                docfin = "";
                docfin += RBopc4.getText();
                precio2 = precio2 + 50;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("Otra salsa: $5");
                ChBopc2.setText("Limon extra: $5 ");
                ChBopc3.setText("Tortilla extra: $10");
                
            }
        }
        //hamburguesas
        if (CBmenu.getSelectedIndex() == 3) {
            docfin = "";
            precio3 = 0;
            if (RBopc1.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                docfin = "";
                docfin += RBopc1.getText();
                precio3 = precio3 + 150;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("Jitomate: $5");
                ChBopc2.setText("Cebolla: $5 ");
                ChBopc3.setText("Ketchup: $5");
            }
            if (RBopc2.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                docfin = "";
                docfin += RBopc2.getText();
                precio3 = precio3 + 100;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("Jitomate: $5");
                ChBopc2.setText("Ketchup: $5 ");
                ChBopc3.setText("Cebolla: $5");
            }
            if (RBopc3.isSelected()) {
                docfin = "";
                docfin += RBopc3.getText();
                precio3 = precio3 + 170;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("Jitomate: $5");
                ChBopc2.setText("Ketchup: $5 ");
                ChBopc3.setText("Cebolla: $5");
            }
            if (RBopc4.isSelected()) {
                docfin = "";
                docfin += RBopc4.getText();
                precio3 = precio3 + 150;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("Jitomate: $5");
                ChBopc2.setText("Ketchup: $5 ");
                ChBopc3.setText("Cebolla: $5");
            }
        }
        //sandwich
        if (CBmenu.getSelectedIndex() == 4) {
            docfin = "";
            precio4 = 0;
            if (RBopc1.isSelected()) {
                docfin = "";
                docfin += RBopc1.getText();
                precio4 = precio4 + 30;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("Crema: $5");
                ChBopc2.setText("Lechuga: $5 ");
                ChBopc3.setText("Cebolla: $5");
            }
            if (RBopc2.isSelected()) {
                docfin = "";
                docfin += RBopc2.getText();
                precio4 = precio4 + 25;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("Col: $5");
                ChBopc2.setText("Frijoles: $5 ");
                ChBopc3.setText("Cebolla: $5");
            }
            if (RBopc3.isSelected()) {
                docfin = "";
                docfin += RBopc3.getText();
                precio4 = precio4 + 20;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("crema: $5");
                ChBopc2.setText("Jamon: $5 ");
                ChBopc3.setText("Chile: $5");
            }
            if (RBopc4.isSelected()) {
                docfin = "";
                docfin += RBopc4.getText();
                precio4 = precio4 + 25;
                ChBopc1.setVisible(true);
                ChBopc2.setVisible(true);
                ChBopc3.setVisible(true);
                ChBopc1.setText("crema: $5");
                ChBopc2.setText("Cebolla: $5 ");
                ChBopc3.setText("Jitomate: $5");
            }
        }
        return docfin;
    }
    
    public void agarrar2() {
        //snacks
        if (CBmenu.getSelectedIndex() == 1) {
            if (RBopc1.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Chocolate: $3");
                x = 3;
                ChBopc2.setText("Chispas: $3 ");
                y = 3;
                ChBopc3.setText("Fresas: $5");
                z = 5;
                Chb(precio1, x, y, z);
            }
            if (RBopc2.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Chamoy: $5");
                x = 5;
                ChBopc2.setText("Salchicha: $3");
                y = 3;
                ChBopc3.setText("Cueritos: $3");
                z = 3;
                Chb(precio1, x, y, z);
            }
            if (RBopc3.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Salchica: $3");
                x = 3;
                ChBopc2.setText("Chile: $5");
                y = 5;
                ChBopc3.setText("Limon: $3");
                z = 3;
                Chb(precio1, x, y, z);
            }
            if (RBopc4.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Chile: $5");
                x = 5;
                ChBopc2.setText("Limon: $3 ");
                y = 3;
                ChBopc3.setText("sal: $3");
                z = 3;
                Chb(precio1, x, y, z);
            }
        }
        //tacos
        if (CBmenu.getSelectedIndex() == 2) {
            if (RBopc1.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Otra salsa: $5");
                x = 5;
                ChBopc2.setText("Limon extra: $5 ");
                y = 5;
                ChBopc3.setText("Tortilla extra: $10");
                z = 10;
                Chb(precio2, x, y, z);
            }
            if (RBopc2.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Otra salsa: $5");
                x = 5;
                ChBopc2.setText("Limon extra: $5 ");
                y = 5;
                ChBopc3.setText("Tortilla extra: $10");
                z = 10;
                Chb(precio2, x, y, z);
            }
            if (RBopc3.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Otra salsa: $5");
                x = 5;
                ChBopc2.setText("Limon extra: $5 ");
                y = 5;
                ChBopc3.setText("Tortilla extra: $10");
                z = 10;
                Chb(precio2, x, y, z);
            }
            if (RBopc4.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Otra salsa: $5");
                x = 5;
                ChBopc2.setText("Limon extra: $5 ");
                y = 5;
                ChBopc3.setText("Tortilla extra: $10");
                z = 10;
                Chb(precio2, x, y, z);
            }
        }
        //hamburguesas
        if (CBmenu.getSelectedIndex() == 3) {
            if (RBopc1.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Jitomate: $5");
                x = 5;
                ChBopc2.setText("Cebolla: $5 ");
                y = 5;
                ChBopc3.setText("Ketchup: $5");
                z = 5;
                Chb(precio3, x, y, z);
            }
            if (RBopc2.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Jitomate: $5");
                x = 5;
                ChBopc2.setText("Ketchup: $5 ");
                y = 5;
                ChBopc3.setText("Cebolla: $5");
                z = 5;
                Chb(precio3, x, y, z);
            }
            if (RBopc3.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Jitomate: $5");
                x = 5;
                ChBopc2.setText("Ketchup: $5 ");
                y = 5;
                ChBopc3.setText("Cebolla: $5");
                z = 5;
                Chb(precio3, x, y, z);
            }
            if (RBopc4.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Jitomate: $5");
                x = 5;
                ChBopc2.setText("Ketchup: $5 ");
                y = 5;
                ChBopc3.setText("Cebolla: $5");
                z = 5;
                Chb(precio3, x, y, z);
            }
        }
        //sandwich
        if (CBmenu.getSelectedIndex() == 4) {
            if (RBopc1.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Crema: $5");
                x = 5;
                ChBopc2.setText("Lechuga: $5 ");
                y = 5;
                ChBopc3.setText("Cebolla: $5");
                z = 5;
                Chb(precio4, x, y, z);
            }
            if (RBopc2.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("Col: $5");
                x = 5;
                ChBopc2.setText("Frijoles: $5 ");
                y = 5;
                ChBopc3.setText("Cebolla: $5");
                z = 5;
                Chb(precio4, x, y, z);
            }
            if (RBopc3.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("crema: $5");
                x = 5;
                ChBopc2.setText("Jamon: $5 ");
                y = 5;
                ChBopc3.setText("Chile: $5");
                z = 5;
                Chb(precio4, x, y, z);
            }
            if (RBopc4.isSelected()) {
                x = 0;
                y = 0;
                z = 0;
                
                ChBopc1.setText("crema: $5");
                x = 5;
                ChBopc2.setText("Cebolla: $5 ");
                y = 5;
                ChBopc3.setText("Jitomate: $5");
                z = 5;
                Chb(precio4, x, y, z);
            }
        }
        
    }
    
    public String Chb(int precio, int x1, int y2, int z3) {
        docfin2 = "";
        int precio0 = 0;
        
        if (!ChBopc1.isSelected() && !ChBopc2.isSelected() && !ChBopc3.isSelected()) {
            precio0 = precio0 + 0;
        } else if (ChBopc1.isSelected() && ChBopc2.isSelected() && ChBopc3.isSelected()) {
            docfin += "\n" + ChBopc1.getText() + "\n" + ChBopc2.getText() + "\n" + ChBopc3.getText() + "\n";
            precio0 = precio0 + x + y + z;
            
        } else if (ChBopc1.isSelected() && ChBopc2.isSelected()) {
            docfin += "\n" + ChBopc1.getText() + "\n" + ChBopc2.getText() + "\n";
            precio0 = precio0 + x + y;
            
        } else if (ChBopc2.isSelected() && ChBopc3.isSelected()) {
            docfin += "\n" + ChBopc2.getText() + "\n" + ChBopc3.getText() + "\n";
            precio0 = precio0 + y + z;
            
        } else if (ChBopc1.isSelected() && ChBopc3.isSelected()) {
            docfin += "\n" + ChBopc1.getText() + "\n" + ChBopc3.getText() + "\n";
            precio0 = precio0 + x + z;
        } else if (ChBopc1.isSelected()) {
            docfin += "\n" + ChBopc1.getText() + "\n";
            precio0 = precio0 + x;
        } else if (ChBopc2.isSelected()) {
            docfin += "\n" + ChBopc2.getText() + "\n";
            precio0 = precio0 + y;
        } else if (ChBopc3.isSelected()) {
            docfin += "\n" + ChBopc3.getText() + "\n";
            precio0 = precio0 + z;
        }
        
        docfin2 += precio0 + precio;
        
        return docfin2;
    }
}
