/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SegundoParcial.Graficos;

import javax.swing.JOptionPane;

/**
 *
 * @author yaser
 */
public class RadioButton extends javax.swing.JFrame {

    /**
     * Creates new form RadioButton
     */
    public RadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGTipoDeCiclo = new javax.swing.ButtonGroup();
        rbtnCuatrimestre = new javax.swing.JRadioButton();
        rbtnSemestre = new javax.swing.JRadioButton();
        btnEvaluar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnArchivo = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        btnEdicion = new javax.swing.JMenu();
        btnAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Radio");
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        btnGTipoDeCiclo.add(rbtnCuatrimestre);
        rbtnCuatrimestre.setText("Cuatrimestre");
        rbtnCuatrimestre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtnCuatrimestre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbtnCuatrimestre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rbtnCuatrimestre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(rbtnCuatrimestre);
        rbtnCuatrimestre.setBounds(170, 60, 90, 50);

        btnGTipoDeCiclo.add(rbtnSemestre);
        rbtnSemestre.setText("Semestre");
        rbtnSemestre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtnSemestre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rbtnSemestre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rbtnSemestre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rbtnSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSemestreActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnSemestre);
        rbtnSemestre.setBounds(80, 60, 90, 50);

        btnEvaluar.setText("Evaluar");
        btnEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEvaluar);
        btnEvaluar.setBounds(120, 180, 72, 22);

        btnArchivo.setText("Archivo");

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnArchivo.add(btnSalir);

        jMenuBar1.add(btnArchivo);

        btnEdicion.setText("Edición");

        btnAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnAcercaDe.setText("Acerca De");
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });
        btnEdicion.add(btnAcercaDe);

        jMenuBar1.add(btnEdicion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
        JOptionPane.showMessageDialog(rootPane, 
        "Pruebas\n Yetzrai Abisai Vazquez Moreno \n 21AL7207489 \n Programación Visual", 
        "Información", 
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAcercaDeActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int x = 1;
        x = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro de que quiere salir?");
        if(x == 0)
        {
        System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void rbtnSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSemestreActionPerformed

    private void btnEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarActionPerformed
        
      
        if(rbtnCuatrimestre.isSelected())
        {
            System.out.println("Cuatrimestre");
        }else if(rbtnSemestre.isSelected())
        {
            System.out.println("Semestre");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Escoja una opción", "Tipo de Ciclo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEvaluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAcercaDe;
    private javax.swing.JMenu btnArchivo;
    private javax.swing.JMenu btnEdicion;
    private javax.swing.JButton btnEvaluar;
    private javax.swing.ButtonGroup btnGTipoDeCiclo;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton rbtnCuatrimestre;
    private javax.swing.JRadioButton rbtnSemestre;
    // End of variables declaration//GEN-END:variables
}
